environment:
  matrix:
    - MINICONDA: C:\Miniconda-x64
    - MINICONDA: C:\Miniconda35-x64
    - MINICONDA: C:\Miniconda36-x64
    - MINICONDA: C:\Miniconda37-x64
install:
  - call "%MINICONDA%\\Scripts\\activate.bat"
  - conda config --set always_yes yes
  - conda config --add channels conda-forge
  - conda install --yes "pip" "setuptools>=27.3"
  - conda install --yes "six>=1.5" "pyopenssl" "ligo-segments>=1.0.0"
  - conda install --yes "pytest>=3.1" "pytest-cov"
build_script:
  - python -m pip install .
test_script:
  - python -m pip install "mock ; python_version < '3.0'"
  - python -m pytest --pyargs gwdatafind --cov gwdatafind --junitxml=junit.xml
on_success:
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\junit.xml))
