stages:
  - build
  - test
  - package
  - deploy

.dist: &build-artifact
  stage: package
  after_script:
    - ls -l dist/
  artifacts:
    expire_in: 3h
    paths:
      - dist

# -- build ------------------

package:tarball:
  <<: *build-artifact
  stage: build
  image: python:3.6
  script:
    - python -m pip install setuptools
    - python setup.py sdist bdist_wheel

# -- test -------------------

.test: &test
  stage: test
  image: python
  before_script:
    - python -m pip install dist/gwdatafind*tar.gz
    - python -m pip install
          "pytest>=2.8.0"
          "pytest-cov"
          "mock ; python_version < '3'"
  script:
    - python -m pytest --pyargs gwdatafind --cov-report= --cov=gwdatafind
    - coverage run -a -m gwdatafind --help
    - coverage report

test:python2.7:
  <<: *test
  image: python:2.7

test:python3.5:
  <<: *test
  image: python:3.5

test:python3.6:
  <<: *test
  image: python:3.6

test:python3.7:
  <<: *test
  image: python:3.7

doc:
  stage: test
  image: python:3.6
  before_script:
    - python -m pip install sphinx
  script:
    - python -m pip install .  # to get dependencies
    - python setup.py build_sphinx
  artifacts:
    paths:
      - build/sphinx/html

# -- package ----------------

.package:el: &package-el
  <<: *build-artifact
  before_script:
    - yum install -yq
          rpm-build
          epel-rpm-macros
          python-rpm-macros
          python-setuptools
          python2-six
          pyOpenSSL
          lal-python
          python2-ligo-segments
          python2-pytest
          python2-mock
  script:
    - python setup.py sdist
    - rpmbuild -tb dist/gwdatafind*.tar.gz
    - mv -v ~/rpmbuild/RPMS/*/python*-gwdatafind-*.rpm dist/
    - rm -rf dist/*.tar.gz

.package:debian: &package-debian
  <<: *build-artifact
  before_script:
    - apt-get update -yqq
    - apt-get install -yq
          dpkg-dev
          debhelper
          dh-python
          python-all-dev
          python3-all-dev
          python-setuptools
          python3-setuptools
          python-six
          python3-six
          python-openssl
          python3-openssl
          lal-python
          lal-python3
          python-ligo-segments
          python3-ligo-segments
          python-pytest
          python3-pytest
          python-mock
  script:
    - pushd .
    - python setup.py sdist
    - version=$(python setup.py --version)
    - cd dist
    - tar -xf gwdatafind-${version}.tar.gz
    - cd gwdatafind-${version}
    - dpkg-buildpackage -us -uc -b
    - popd
    - rm -rf dist/gwdatafind*

package:el:7:
  <<: *package-el
  image: ligo/base:el7

package:debian:jessie:
  <<: *package-debian
  image: ligo/base:jessie

package:debian:stretch:
  <<: *package-debian
  image: ligo/base:stretch
